<?php
/**
 * @file
 *
 * Provides Views Bootstrap Demo install and uninstall routines.
 */

/**
 * Implements hook_install().
 */
function views_bootstrap_demo_install() {
  _views_bootstrap_demo_create_nodes();
}

/**
 * Implements hook_uninstall().
 */
function views_bootstrap_demo_uninstall() {
  $nids_fids = db_query('
    SELECT n.nid, i.field_image_fid
    FROM {node} n
    LEFT JOIN {field_data_field_image} i ON i.entity_id = n.nid
    WHERE type = :type
    ', array(':type' => 'views_bootstrap_demo'))
    ->fetchAllKeyed();

  // Delete the nodes
  node_delete_multiple(array_keys($nids_fids));

  // Fully delete the images (don't wait for cleanup)
  foreach (array_values($nids_fids) as $fid) {
    file_delete($fid);
  }

  // Remove the directory we were storing our node images in.
  backdrop_rmdir('public://views_bootstrap_demo');

  // Drop now-empty tables we created from the db.
  db_query('
    DROP TABLE IF EXISTS {field_data_field_snippet},{field_revision_field_snippet}
    ')->execute();

  backdrop_set_message(t('@count Views Bootstrap Demo nodes have been deleted.', array('@count' => count($nids_fids))));
}

/**
 * Create some demonstration nodes for Views Bootstrap Demo.
 */
function _views_bootstrap_demo_create_nodes() {
  // Destination directory for images in demo nodes
  $image_dir = 'public://views_bootstrap_demo';
  if (!file_prepare_directory($image_dir, FILE_CREATE_DIRECTORY | FILE_MODIFY_PERMISSIONS)) {
    backdrop_set_message(t('Unable to create or write  to directory %dir.',
      array('%dir' => $image_dir)), 'error');
    return;
  }
  global $base_url;
  $image_url_base = $base_url . '/' . backdrop_get_path('module', 'views_bootstrap_demo') . '/images/image_';

  $num_to_create = 6;

  $num_existing_nodes = db_query('
    SELECT COUNT(1)
    FROM {node}
    WHERE type = :type
    ', array(':type' => 'views_bootstrap_demo'))
    ->fetchField();

  for ($i = 0; $i < $num_to_create; $i++) {
    $n = $num_existing_nodes + 1 + $i;
    $image_url = $image_url_base . (1 + $n % 6) . '.jpg';
    $new_file = system_retrieve_file($image_url, $image_dir, TRUE);
    $node = entity_create('node', array(
      'title' => t('Title-@n', array('@n' => $n)),
      'body' => array(
        LANGUAGE_NONE => array(
          array(
            'value' => t('This is body text @n.', array('@n' => $n)),
            'format' => 'filtered_html',
          ),
        ),
      ),
      'field_snippet' => array(
        LANGUAGE_NONE => array(
          array(
            'value' => t('Snippet-@n', array('@n' => $n)),
          ),
        ),
      ),
      'field_image' => array(
        LANGUAGE_NONE => array(
          array(
            'fid' => $new_file->fid,
          ),
        ),
      ),
      'uid' => 1,
      'promote' => 0,
      'status' => 1,
      'comment' => 0,
      'type' => 'views_bootstrap_demo',
    ));
    $node->save();
  }
  backdrop_set_message(t('@num Views Bootstrap Demo nodes have been created.', array('@num' => $num_to_create)));
}
